; GLOBAL: These apply to ANY model you load manually via command line
[*]
flash-attn = on
n-gpu-layers = 99
jinja = true
ubatch-size = 8192
cache-type-k = q8_0
cache-type-v = q8_0
parallel = 1
main-gpu = 1

; SPECIFIC: Coding Model (Matched to Port 11434)
[Qwen_Qwen3.5-9B-Q6_K.gguf]
alias = qwen3:9b
ctx-size = 262144   ; 131072
split-mode = none     ; Keep 100% on GPU 1

; SPECIFIC: Embedding Model (Matched to Port 11435)
[mxbai-embed-large-v1-f16.gguf]
alias = embedding-model
split-mode = none
main-gpu = 1
ctx-size = 1024
embedding = true