[*]
ctx-size = 131072
n-gpu-layers = 99
flash-attn = on
cache-type-k = q8_0
cache-type-v = q8_0
parallel = 1
cache-ram = -1
jinja = true
kv-unified = true
no-mmproj = true
batch-size = 512
ubatch-size = 512
checkpoint-min-step = 2048
chat-template-kwargs = {"preserve_thinking":true}
reasoning-preserve = 1
; no-context-shift = true


[qwen3.8-27B]
model = /home/humberto/models/unsloth/Qwen3.8-27B-UD-Q4_K_XL.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
tensor-split = 0.55,0.45
chat-template-kwargs = {"preserve_thinking":true}
; chat-template-file = /home/humberto/models/qwen-chat-template.jinja


[qwen3.6-27B]
model = /home/humberto/models/williamliao/Qwen3.6-27B-NVFP4.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
tensor-split = 0.55,0.45
chat-template-kwargs = {"preserve_thinking":true}
chat-template-file = /home/humberto/models/qwen-chat-template.jinja

[qwen3.6-35B]
model = /home/humberto/models/williamliao/Qwen3.6-35B-A3B-NVFP4.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
tensor-split = 0.55,0.45
chat-template-kwargs = {"preserve_thinking":true}
chat-template-file = /home/humberto/models/qwen-chat-template.jinja

[gemma4-31B]
model = /home/humberto/models/freedomaisvr/gemma-4-31B-it-NVFP4.gguf
model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-31B-it-MTP-Q8_0.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1
top-p = 0.95
top-k = 64
presence-penalty = 0.0
repeat-penalty = 1.0
tensor-split = 0.55,0.45


[gemma4-26B]
model = /home/humberto/models/freedomaisvr/gemma-4-26b-NVFP4.gguf
model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-26B-A4B-it-MTP-Q8_0.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1
top-p = 0.95
top-k = 64
presence-penalty = 0.0
repeat-penalty = 1.0
tensor-split = 0.55,0.45



; qwopus 3.6 27b coder
; https://x.com/KyleHessling1/status/2065218054150377663
; https://huggingface.co/Jackrong/Qwopus3.6-27B-Coder-MTP-GGUF

[qwopus3.6-27B]
; model = /home/humberto/models/jackrong/Qwopus3.6-27B-Coder-MTP-Q5_K_M.gguf
model = /home/humberto/models/jackrong/Qwopus3.6-27B-Coder-Compat-MTP-Q4_K_M.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1.0
top-p = 0.95
; tensor-split = 0.55,0.45
chat-template-file = /home/humberto/models/qwen-chat-template.jinja

[qwopus3.6-27B-nothink]
model = /home/humberto/models/jackrong/Qwopus3.6-27B-Coder-Compat-MTP-Q4_K_M.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1.0
top-p = 0.95
reasoning = off
chat-template-file = /home/humberto/models/qwen-chat-template.jinja

[qwopus3.6-35B-nothink]
model = /home/humberto/models/jackrong/Qwopus3.6-35B-A3B-Coder-MTP-Q4_K_M.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
reasoning = off
temp = 1.0
top-p = 0.95
chat-template-file = /home/humberto/models/qwen-chat-template.jinja

; nex n2 is based on qwen 3.5 35b MOE
[nex-n2-mini]
model = /home/humberto/models/freedomaisvr/north-mini-code-1.0-nvfp4.gguf
temp = 0.7
top-p = 0.95
top-k = 40
ctx-size = 262144

[north-mini-code-1.0]
model = /home/humberto/models/freedomaisvr/north-mini-code-1.0-nvfp4.gguf
temp = 1
top-p = 0.95
ctx-size = 262144

[nemotron3-30B]
model = /home/humberto/models/iwakurarein/Nemotron-3-Nano-30B-A3B-NVFP4.gguf
temp = 0.6
top-p = 0.95
min-p = 0.01
ctx-size = 262144

; https://huggingface.co/s-batman/Ornith-1.0-35B-NVFP4-MTP-GGUF
[ornith-35b]
model = /home/humberto/models/sbatman/ornith-1.0-35b-NVFP4-MTP.gguf
spec-type = draft-mtp
reasoning-budget = 2048
reasoning-budget-message = "I have thought enough. Let me give my answer now."
temp = 0.9
top-p = 0.95
top-k = 20
min-p = 0.01
repeat-penalty = 1.0
ctx-size = 262144
tensor-split = 0.52,0.48

; ,ngram-mod
; spec-draft-n-max = 3
; spec-ngram-mod-n-match = 24
; spec-ngram-mod-n-min = 48
; spec-ngram-mod-n-max = 64

[qwen3.6-27B-thinking-cap]
;model = /home/humberto/models/bottlecapai/ThinkingCap-Qwen3.6-27B-Q4_K_M.gguf
model = /home/humberto/models/protolabsai/ThinkingCap-Qwen3.6-27B-NVFP4-MTP.gguf
chat-template-file = /home/humberto/models/qwen-chat-template.jinja
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
tensor-split = 0.54,0.46
ctx-size = 262144

[glm4.7-flash]
model = /home/humberto/models/freedomaisvr/glm-4.7-flash-nvfp4.gguf
temp = 1.0
top-p = 0.95
ctx-size = 202752

[glm4.7-flash-reap]
model = /home/humberto/models/unsloth/GLM-4.7-Flash-REAP-23B-A3B-UD-Q6_K_XL.gguf
temp = 1.0
top-p = 0.95
ctx-size = 202752

[tess-4-27B]
model = /home/humberto/models/migtissera/Tess-4-27B-Q4_K_M.gguf
; model = /home/humberto/models/migtissera/Tess-4-27B-Q6_K.gguf
spec-draft-model = /home/humberto/models/migtissera/mtp-Tess-4-27B-Q4_K_M.gguf
; spec-draft-model = /home/humberto/models/migtissera/mtp-Tess-4-27B-Q8_0.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
; ctx-size = 102400
tensor-split = 0.58,0.42
chat-template-file = /home/humberto/models/qwen-chat-template.jinja



; TESTES ANTIGOS

;https://unsloth.ai/docs/models/nemotron-3#llama-server-serving-and-deployment
; [nemotron3-30B-general]
; model = /home/humberto/models/iwakurarein/Nemotron-3-Nano-30B-A3B-NVFP4.gguf
; temp = 1.0
; top-p = 1.0


; https://unsloth.ai/docs/models/nemotron-3#llama-server-serving-and-deployment
; [nemotron3-30B]
; model = /home/humberto/models/iwakurarein/Nemotron-3-Nano-30B-A3B-NVFP4.gguf
; temp = 0.6
; top-p = 0.95
; min-p = 0.01

; [qwen3.6-27B]
; model = /home/humberto/models/unsloth/qwen3.6-mtp/Qwen3.6-27B-UD-Q4_K_XL.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 3
; temp = 0.6
; top-p = 0.95
; top-k = 20
; min-p = 0.00
; presence-penalty = 0.0
; repeat-penalty = 1.0
; tensor-split = 0.55,0.45
; chat-template-kwargs = {"preserve_thinking":true}

; [qwen3.6-35B-mtp]
; model = /home/humberto/models/unsloth/qwen3.6-mtp/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 3
; temp = 0.6
; top-p = 0.95
; top-k = 20
; min-p = 0.00
; presence-penalty = 0.0
; repeat-penalty = 1.0
; tensor-split = 0.55,0.45
; chat-template-kwargs = {"preserve_thinking":true}

; [qwen3.6-35B]
; model = /home/humberto/models/unsloth/qwen3.6/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
; temp = 0.6
; top-p = 0.95
; top-k = 20
; min-p = 0.00
; presence-penalty = 0.0
; repeat-penalty = 1.0
; tensor-split = 0.55,0.45
; chat-template-kwargs = {"preserve_thinking":true}




; [gemma4-12B-mtp]
; model = /home/humberto/models/unsloth/gemma4/gemma-4-12b-it-UD-Q4_K_XL.gguf
; model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-12B-it-MTP-Q8_0.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 3
; temp = 1
; top-p = 0.95
; top-k = 64
; presence-penalty = 0.0
; repeat-penalty = 1.0
; tensor-split = 1,0
; cache-type-k = bf16
; cache-type-v = bf16


; [gemma4-12B-nvfp4]
; model = /home/humberto/models/libertaidai/Gemma-4-12B-IT-NVFP4-Q8_0.gguf
; model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-12B-it-MTP-Q8_0.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 3
; temp = 1
; top-p = 0.95
; top-k = 64
; presence-penalty = 0.0
; repeat-penalty = 1.0
; tensor-split = 1,0
; cache-type-k = bf16
; cache-type-v = bf16
; chat-template-kwargs = {"enable-thinking":false}

; [gemma4-12B-nvfp4-nothink]
; model = /home/humberto/models/libertaidai/Gemma-4-12B-IT-NVFP4-Q8_0.gguf
; model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-12B-it-MTP-Q8_0.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 3
; temp = 1
; top-p = 0.95
; top-k = 64
; presence-penalty = 0.0
; repeat-penalty = 1.0
; tensor-split = 1,0
; cache-type-k = bf16
; cache-type-v = bf16



; [gemma4-12B-qat]
; model = /home/humberto/models/unsloth/gemma4-qat/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
; temp = 1
; top-p = 0.95
; top-k = 64
; presence-penalty = 0.0
; repeat-penalty = 1.0
; tensor-split = 1,0
; cache-type-k = bf16
; cache-type-v = bf16


; [gemma4-12B-qat-mtp]
; model = /home/humberto/models/unsloth/gemma4-qat/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
; model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-12B-it-MTP-Q8_0.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 3
; temp = 1
; top-p = 0.95
; top-k = 64
; presence-penalty = 0.0
; repeat-penalty = 1.0
; tensor-split = 1,0
; cache-type-k = bf16
; cache-type-v = bf16


; [gemma4-26B]
; model = /home/humberto/models/unsloth/gemma4/gemma-4-26B-A4B-it-UD-Q5_K_S.gguf
; temp = 1
; top-p = 0.95
; top-k = 64
; presence-penalty = 0.0
; repeat-penalty = 1.0
; ; min-p = 0.00

; [gemma4-26B-mtp]
; model = /home/humberto/models/unsloth/gemma4/gemma-4-26B-A4B-it-UD-Q5_K_S.gguf
; model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-26B-A4B-it-MTP-Q8_0.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 3
; temp = 1
; top-p = 0.95
; top-k = 64
; presence-penalty = 0.0
; repeat-penalty = 1.0


; [gemma4-31B]
; model = /home/humberto/models/unsloth/gemma4/gemma-4-31B-it-UD-Q4_K_XL.gguf
; temp = 1
; top-p = 0.95
; top-k = 64
; presence-penalty = 0.0
; repeat-penalty = 1.0
; tensor-split = 0.55,0.45

; [gemma4-31B-mtp]
; model = /home/humberto/models/unsloth/gemma4/gemma-4-31B-it-UD-Q4_K_XL.gguf
; model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-31B-it-MTP-Q8_0.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 3
; temp = 1
; top-p = 0.95
; top-k = 64
; presence-penalty = 0.0
; repeat-penalty = 1.0
; ctx-size = 112640
; tensor-split = 0.55,0.45


; [gemma4-31B-qat]
; model = /home/humberto/models/unsloth/gemma4-qat/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf
; temp = 1
; top-p = 0.95
; top-k = 64
; presence-penalty = 0.0
; repeat-penalty = 1.0
; ctx-size = 112640
; tensor-split = 0.55,0.45


; [gemma4-31B-qat-mtp]
; model = /home/humberto/models/unsloth/gemma4-qat/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf
; model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-31B-it-MTP-Q8_0.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 3
; temp = 1
; top-p = 0.95
; top-k = 64
; presence-penalty = 0.0
; repeat-penalty = 1.0
; ctx-size = 112640
; tensor-split = 0.55,0.45

; [gemopus-4-26B]
; model = /home/humberto/models/jackrong/Gemopus-4-26B-A4B-it-Preview-Q5_K_M.gguf
; temp = 1
; top-p = 0.95
; top-k = 64
; presence-penalty = 0.0
; repeat-penalty = 1.0

; [gemopus4-31B]
; model = /home/humberto/models/jackrong/Gemopus-4-31B-it-Q5_K_S.gguf
; temp = 1
; top-p = 0.95
; top-k = 64
; presence-penalty = 0.0
; repeat-penalty = 1.0


; [qwopus3.6-35B]
; model = /home/humberto/models/jackrong/Qwopus3.6-35B-A3B-v1-Q4_K_M.gguf
; temp = 1.0
; top-p = 0.95
; top-k = 20
; min-p = 0.00
; presence-penalty = 0.0
; repeat-penalty = 1.0
; chat-template-kwargs = {"preserve_thinking":true}
; rope-scaling = yarn
; rope-scale = 4
; yarn-orig-ctx = 32768



; [qwopus3.6-35B-mtp]
; model = /home/humberto/models/jackrong/Qwopus3.6-35B-A3B-v1-MTP-Q4_K_M.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 3
; temp = 1.0
; top-p = 0.95
; top-k = 20
; min-p = 0.00
; presence-penalty = 0.0
; repeat-penalty = 1.0
; chat-template-kwargs = {"preserve_thinking":true}
; rope-scaling = yarn
; rope-scale = 4
; yarn-orig-ctx = 32768



; [qwopus3.6-27B]
; model = /home/humberto/models/jackrong/Qwopus3.6-27B-v2-MTP-Q4_K_M.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 3
; temp = 1.0
; top-p = 0.95
; top-k = 20
; min-p = 0.00
; presence-penalty = 0.0
; repeat-penalty = 1.0
; chat-template-kwargs = {"preserve_thinking":true}
; rope-scaling = yarn
; rope-scale = 4
; yarn-orig-ctx = 32768


; [qwen3.6-35B-mtp]
; model = /home/humberto/models/unsloth/qwen3.6-mtp/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 3
; temp = 0.6tensor-split = 0.55,0.45
; top-p = 0.95
; top-k = 20
; min-p = 0.00
; presence-penalty = 0.0
; repeat-penalty = 1.0
; tensor-split = 0.55,0.45

; https://huggingface.co/nilayparikh/Qwen3.6-27B-Text-NVFP4-MTP-GGUF
; [qwen3.6-27B-NVFP4]
; model = /home/humberto/models/nilayparikh/qwen3.6-27b-text-nvfp4-mtp.gguf
; spec-type = draft-mtp,ngram-mod
; spec-draft-n-max = 3
; temp = 0.6
; top-p = 0.95
; top-k = 20
; min-p = 0.00
; presence-penalty = 0.0
; repeat-penalty = 1.0
; tensor-split = 0.57,0.43
; ; batch-size = 768
; ; ubatch-size = 768
; chat-template-kwargs = {"preserve_thinking":true}
; cache-type-k = bf16
; cache-type-v = bf16

; [qwen3.6-35B-NVFP4]
; model = /home/humberto/models/freedomaisvr/qwen3.6-35b-a3b-nvfp4.gguf
; ; spec-type = draft-mtp
; ; spec-draft-n-max = 3
; temp = 0.6
; top-p = 0.95
; top-k = 20
; min-p = 0.00
; presence-penalty = 0.0
; repeat-penalty = 1.0
; batch-size = 1024
; ubatch-size = 1024
; chat-template-kwargs = {"preserve_thinking":true}
; cache-type-k = bf16
; cache-type-v = bf16
