[*]
ctx-size = 131072
n-gpu-layers = 99
flash-attn = on
cache-type-k = q8_0
cache-type-v = q8_0
parallel = 1
cache-ram = -1
jinja = true
kv-unified = true
no-context-shift = true
no-mmproj = true


[qwen3.6-27B]
model = /home/humberto/models/unsloth/mtp/Qwen3.6-27B-UD-Q5_K_XL.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
tensor-split = 0.55,0.45
batch-size = 512
ubatch-size = 512
chat-template-kwargs = {"preserve_thinking": true} 

; Model 2: Qwen3.6-35B-A3B MTP (Q4_K_XL quant)
[qwen3.6-35B]
model = /home/humberto/models/unsloth/mtp/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
tensor-split = 0.55,0.45
batch-size = 512
ubatch-size = 512
chat-template-kwargs = {"preserve_thinking": true} 


[qwen3.6-35B-256k]
model = /home/humberto/models/unsloth/mtp/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
tensor-split = 0.51,0.49
batch-size = 256
ubatch-size = 256
chat-template-kwargs = {"preserve_thinking": true} 
cache-type-k = q8_0
cache-type-v = q8_0
log-verbosity = 4
ctx-size = 262144