[*]
ctx-size = 131072
n-gpu-layers = 99
flash-attn = on
cache-type-k = q8_0
cache-type-v = q8_0
parallel = 1
cache-ram = -1
jinja = true
kv-unified = true
no-context-shift = true
no-mmproj = true
batch-size = 512
ubatch-size = 512
checkpoint-min-step = 2048




[qwen3.6-27B]
model = /home/humberto/models/unsloth/qwen3.6-mtp/Qwen3.6-27B-UD-Q4_K_XL.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
tensor-split = 0.55,0.45
chat-template-kwargs = {"preserve_thinking":true} 

[qwen3.6-35B-mtp]
model = /home/humberto/models/unsloth/qwen3.6-mtp/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
tensor-split = 0.55,0.45
chat-template-kwargs = {"preserve_thinking":true} 

[qwen3.6-35B]
model = /home/humberto/models/unsloth/qwen3.6/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
tensor-split = 0.55,0.45
chat-template-kwargs = {"preserve_thinking":true} 




[gemma4-12B-mtp]
model = /home/humberto/models/unsloth/gemma4/gemma-4-12b-it-UD-Q4_K_XL.gguf
model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-12B-it-MTP-Q8_0.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1 
top-p = 0.95  
top-k = 64  
presence-penalty = 0.0 
repeat-penalty = 1.0 
tensor-split = 1,0
cache-type-k = bf16
cache-type-v = bf16


[gemma4-12B-nvfp4]
model = /home/humberto/models/libertaidai/Gemma-4-12B-IT-NVFP4-Q8_0.gguf
model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-12B-it-MTP-Q8_0.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1 
top-p = 0.95  
top-k = 64  
presence-penalty = 0.0 
repeat-penalty = 1.0 
tensor-split = 1,0
cache-type-k = bf16
cache-type-v = bf16
chat-template-kwargs = {"enable-thinking":false} 

[gemma4-12B-nvfp4-nothink]
model = /home/humberto/models/libertaidai/Gemma-4-12B-IT-NVFP4-Q8_0.gguf
model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-12B-it-MTP-Q8_0.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1 
top-p = 0.95  
top-k = 64  
presence-penalty = 0.0 
repeat-penalty = 1.0 
tensor-split = 1,0
cache-type-k = bf16
cache-type-v = bf16



[gemma4-12B-qat]
model = /home/humberto/models/unsloth/gemma4-qat/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
temp = 1 
top-p = 0.95  
top-k = 64  
presence-penalty = 0.0 
repeat-penalty = 1.0 
tensor-split = 1,0
cache-type-k = bf16
cache-type-v = bf16


[gemma4-12B-qat-mtp]
model = /home/humberto/models/unsloth/gemma4-qat/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-12B-it-MTP-Q8_0.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1 
top-p = 0.95  
top-k = 64  
presence-penalty = 0.0 
repeat-penalty = 1.0 
tensor-split = 1,0
cache-type-k = bf16
cache-type-v = bf16


[gemma4-26B]
model = /home/humberto/models/unsloth/gemma4/gemma-4-26B-A4B-it-UD-Q5_K_S.gguf
temp = 1 
top-p = 0.95  
top-k = 64  
presence-penalty = 0.0 
repeat-penalty = 1.0 
; min-p = 0.00 

[gemma4-26B-mtp]
model = /home/humberto/models/unsloth/gemma4/gemma-4-26B-A4B-it-UD-Q5_K_S.gguf
model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-26B-A4B-it-MTP-Q8_0.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1 
top-p = 0.95  
top-k = 64  
presence-penalty = 0.0 
repeat-penalty = 1.0 


[gemma4-31B]
model = /home/humberto/models/unsloth/gemma4/gemma-4-31B-it-UD-Q4_K_XL.gguf
temp = 1 
top-p = 0.95  
top-k = 64  
presence-penalty = 0.0 
repeat-penalty = 1.0 
tensor-split = 0.55,0.45

[gemma4-31B-mtp]
model = /home/humberto/models/unsloth/gemma4/gemma-4-31B-it-UD-Q4_K_XL.gguf
model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-31B-it-MTP-Q8_0.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1 
top-p = 0.95  
top-k = 64  
presence-penalty = 0.0 
repeat-penalty = 1.0 
ctx-size = 112640
tensor-split = 0.55,0.45


[gemma4-31B-qat]
model = /home/humberto/models/unsloth/gemma4-qat/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf
temp = 1 
top-p = 0.95  
top-k = 64  
presence-penalty = 0.0 
repeat-penalty = 1.0 
ctx-size = 112640
tensor-split = 0.55,0.45


[gemma4-31B-qat-mtp]
model = /home/humberto/models/unsloth/gemma4-qat/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf
model-draft = /home/humberto/models/unsloth/gemma4-mtp/gemma-4-31B-it-MTP-Q8_0.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1 
top-p = 0.95  
top-k = 64  
presence-penalty = 0.0 
repeat-penalty = 1.0 
ctx-size = 112640
tensor-split = 0.55,0.45

; [gemopus-4-26B]
; model = /home/humberto/models/jackrong/Gemopus-4-26B-A4B-it-Preview-Q5_K_M.gguf
; temp = 1 
; top-p = 0.95  
; top-k = 64  
; presence-penalty = 0.0 
; repeat-penalty = 1.0 

; [gemopus4-31B]
; model = /home/humberto/models/jackrong/Gemopus-4-31B-it-Q5_K_S.gguf
; temp = 1 
; top-p = 0.95  
; top-k = 64  
; presence-penalty = 0.0 
; repeat-penalty = 1.0 


; [qwopus3.6-35B]
; model = /home/humberto/models/jackrong/Qwopus3.6-35B-A3B-v1-Q4_K_M.gguf
; temp = 1.0
; top-p = 0.95
; top-k = 20
; min-p = 0.00
; presence-penalty = 0.0
; repeat-penalty = 1.0
; chat-template-kwargs = {"preserve_thinking":true} 
; rope-scaling = yarn
; rope-scale = 4 
; yarn-orig-ctx = 32768



; [qwopus3.6-35B-mtp]
; model = /home/humberto/models/jackrong/Qwopus3.6-35B-A3B-v1-MTP-Q4_K_M.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 3
; temp = 1.0
; top-p = 0.95
; top-k = 20
; min-p = 0.00
; presence-penalty = 0.0
; repeat-penalty = 1.0
; chat-template-kwargs = {"preserve_thinking":true} 
; rope-scaling = yarn
; rope-scale = 4 
; yarn-orig-ctx = 32768



; [qwopus3.6-27B]
; model = /home/humberto/models/jackrong/Qwopus3.6-27B-v2-MTP-Q4_K_M.gguf
; spec-type = draft-mtp
; spec-draft-n-max = 3
; temp = 1.0
; top-p = 0.95
; top-k = 20
; min-p = 0.00
; presence-penalty = 0.0
; repeat-penalty = 1.0
; chat-template-kwargs = {"preserve_thinking":true} 
; rope-scaling = yarn
; rope-scale = 4 
; yarn-orig-ctx = 32768



;https://unsloth.ai/docs/models/nemotron-3#llama-server-serving-and-deployment
; [nemotron3-30B-general]
; model = /home/humberto/models/iwakurarein/Nemotron-3-Nano-30B-A3B-NVFP4.gguf
; temp = 1.0
; top-p = 1.0


; https://unsloth.ai/docs/models/nemotron-3#llama-server-serving-and-deployment
; [nemotron3-30B]
; model = /home/humberto/models/iwakurarein/Nemotron-3-Nano-30B-A3B-NVFP4.gguf
; temp = 0.6
; top-p = 0.95
; min-p = 0.01


; https://huggingface.co/nilayparikh/Qwen3.6-27B-Text-NVFP4-MTP-GGUF
[qwen3.6-27B-NVFP4]
model = /home/humberto/models/nilayparikh/qwen3.6-27b-text-nvfp4-mtp.gguf
spec-type = draft-mtp,ngram-mod
spec-draft-n-max = 4
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
tensor-split = 0.57,0.43
; batch-size = 768
; ubatch-size = 768
chat-template-kwargs = {"preserve_thinking":true} 
cache-type-k = bf16
cache-type-v = bf16

[qwen3.6-35B-NVFP4]
model = /home/humberto/models/freedomaisvr/qwen3.6-35b-a3b-nvfp4.gguf
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
batch-size = 1024
ubatch-size = 1024
chat-template-kwargs = {"preserve_thinking":true} 
cache-type-k = bf16
cache-type-v = bf16


; qwopus 3.6 27b coder 
; https://x.com/KyleHessling1/status/2065218054150377663
; https://huggingface.co/Jackrong/Qwopus3.6-27B-Coder-MTP-GGUF

[qwopus3.6-27B]
; model = /home/humberto/models/jackrong/Qwopus3.6-27B-Coder-MTP-Q5_K_M.gguf
model = /home/humberto/models/jackrong/Qwopus3.6-27B-Coder-Compat-MTP-Q4_K_M.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
chat-template-kwargs = {"preserve_thinking":true} 
rope-scaling = yarn
rope-scale = 4 
yarn-orig-ctx = 32768
tensor-split = 0.55,0.45

[qwopus3.6-27B-nothink]
; model = /home/humberto/models/jackrong/Qwopus3.6-27B-Coder-MTP-Q5_K_M.gguf
model = /home/humberto/models/jackrong/Qwopus3.6-27B-Coder-Compat-MTP-Q4_K_M.gguf
spec-type = draft-mtp
spec-draft-n-max = 3
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0.0
repeat-penalty = 1.0
chat-template-kwargs = {"enable-thinking":false} 
reasoning-budget = 0
rope-scaling = yarn
rope-scale = 4 
yarn-orig-ctx = 32768
tensor-split = 0.55,0.45

; https://huggingface.co/LibertAIDAI/Nex-N2-mini-NVFP4-GGUF
; https://huggingface.co/nex-agi/Nex-N2-mini
[nex-n2-mini]
model = /home/humberto/models/libertaidai/Nex-N2-mini-NVFP4-Q8_0.gguf
temp = 0.7
top-p = 0.95
top-k = 40

[north-mini-code-1.0]
model = /home/humberto/models/freedomaisvr/north-mini-code-1.0-nvfp4.gguf
temp = 1
top-p = 0.95
cache-type-k = bf16
cache-type-v = bf16
ctx-size = 262144